### ISSUE TITLE
Nginx config issues

### ISSUE THREAD

**Issue by tripflex** [richardtape/testit#1]
Here's some good documents I found while working on this:

http://linuxplayer.org/2013/06/nginx-try-files-on-multiple-named-location-or-server
https://github.com/perusio/wordpress-nginx
https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#
https://www.digitalocean.com/community/questions/nginx-as-proxy-to-wordpress

https://github.com/splitbrain/docker-phpfarm

**Comment by richardtape** [comment]
Bravo. Thanks @tripflex 

(For future me who will forget what this was about) WP Permalinks were broken because Apache wasn't processing the redirects that nginx was making. Throwing a .htaccess file in the data/ dir fixed things.
